
export const RENDER_USERS = 'RENDER_USERS';
export const RENDER_USERS_TABLE = 'RENDER_USERS_TABLE';

export const RENDER_STUDENT = 'RENDER_STUDENT';
export const RENDER_STUDENT_TABLE = 'RENDER_STUDENT_TABLE';

export const RENDER_CITY = 'RENDER_CITY';
export const RENDER_CITY_TABLE = 'RENDER_CITY_TABLE';

export const RENDER_PROFESSOR = 'RENDER_PROFESSOR';
export const RENDER_PROFESSOR_TABLE = 'RENDER_PROFESSOR_TABLE';

export const RENDER_GROUP = 'RENDER_GROUP';
export const RENDER_GROUP_TABLE = 'RENDER_GROUP_TABLE';
